## Week 2: Jupyter Notebook - Pandas Introduction/Overview
Make sure to select your Kernel before starting!

Watch the [Youtube Video](https://www.youtube.com/watch?v=DkjCaAMBGWM&t=1s) I based this notebook from!

### Import Pandas Library/Package
`import pandas as pd`

In [1]:
import pandas as pd

### Optional: Displaying your Dataframe
Don't use for big datasets

In [2]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.max_rows", None)     # Show all rows

### How to make a dataframe
`pd.DataFrame()`

In [3]:
data = {'Name': ['Zophie', 'Alice', 'Bob', 'Charlie'], 
        'Age': [7, 5, 3, 2],
        'Color': ['Gray', 'Black', 'Brown', 'White']
        }                                                       # Called a Python Dictionary

#### Create a data frame
Store the dataframe using the `pd.DataFrame()` function into a variable called `df`

In [5]:
df = pd.DataFrame(data)
df

      Name  Age  Color
0   Zophie    7   Gray
1    Alice    5  Black
2      Bob    3  Brown
3  Charlie    2  White

### Read In Datasets
`pd.read_csv()`
Read in the file from the data folder called `Shot_Visuals_KaylanBigun_NathanTrouve.csv`

Save as `shots`

In [9]:
shots = pd.read_csv('data/Shot_Visuals_KaylanBigun_NathanTrouve.csv')
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`pd.read_json()`

`pd.read_excel(x, sheet_name)`

In [11]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name = 'Points')

### Basic Functions for Quick Analysis
`df.head()`

Gives you the **FIRST** 5 observations/rows
- If you put a number within the parentheses you will get that number of rows

In [12]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`df.tail()`
Gives you the **LAST** 5 observations/rows

In [13]:
shots.tail()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
467,30-15,2-5,0-1,1.0,4433919.0,NaN,NaN,117,NaN,1,Ad,Nathan Trouve,Far,1.0,Body,-60.793285,-171.818154,NaN,NaN,NaN,NaN,NaN,43.360039,398.064255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Body,NaN
468,30-15,2-5,0-1,NaN,4434580.0,NaN,NaN,117,NaN,2,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-122.080988,-434.136800,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.583503,192.648972,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
469,30-15,2-5,0-1,NaN,4436419.0,NaN,NaN,117,NaN,3,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.231327,439.331070,Down the Line,Backhand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.163774,-243.998803,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
470,30-15,2-5,0-1,NaN,4439640.0,1.0,4439640.0,117,NaN,4,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.187981,228.212440,Down the Line,Forehand,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,149.959230,-172.655184,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,NaN,NaN,NaN
471,40-15,2-5,0-1,1.0,4457669.0,1.0,4457669.0,118,NaN,1,Deuce,Nathan Trouve,Far,1.0,T,12.432847,-233.994483,NaN,NaN,NaN,NaN,1.0,6.873114,449.561909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,20,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,Nathan Trouve,NaN,1st Serve In,T,NaN

`df.sample()`

Gives you a **RANDOM** observation sample

Arguments: frac, random_state

In [15]:
shots.sample(5)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
180,15-15,4-4,0-0,NaN,1785750.0,NaN,NaN,52,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.542449,-429.950312,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-32.301892,346.248639,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,9,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
328,0-0,0-2,0-1,NaN,3229889.0,NaN,NaN,85,NaN,2,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.949289,-447.593389,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.192596,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,15,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,30-30,5-5,0-0,NaN,2373560.0,NaN,NaN,66,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-66.161483,477.009465,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-195.603609,-437.077619,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,11,NaN,Nathan Trouve,Kaylan Bigun,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
291,40-30,5-6,0-0,1.0,2695590.0,NaN,NaN,74,NaN,1,Ad,Nathan Trouve,Far,1.0,Body,-62.441623,-158.629271,NaN,NaN,NaN,NaN,NaN,51.733016,502.726465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,12,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Body,NaN
83,40-40,2-1,0-0,NaN,818479.0,1.0,818479.0,24,1.0,3,Deuce,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-157.292350,521.864698,Down the Line,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-107.802067,18.671260,NaN,NaN,NaN,1.0,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,4,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN

`df.columns`

Gives you all the column names of your dataset

In [16]:
shots.columns

Index(['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick', 'gameNumber', 'tiebreakScore',
       'returnerName', 'shotHitBy', 'InsideOut', 'InsideIn', 'isDoubleFault',
       'pointWonBy', 'lastShotError', 'serveResult', 'serveInPlacement',
       'depth'],
      dtype='object')

In [17]:
shots_excel.columns

Index(['Point', 'Game', 'Set', 'Serve State', 'Match Server',
       'Host Game Score', 'Guest Game Score', 'Point Winner', 'Detail',
       'Break Point', 'Set Point', 'Favorited', 'Start Time', 'Video Time',
       'Duration'],
      dtype='object')

`df.index`

Gives you the index values in the dataframe

In [18]:
shots.index

RangeIndex(start=0, stop=472, step=1)

Use the `list()` function to see all the numbers

In [20]:
list(shots.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471]

`df.info()`

In [21]:
shots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 72 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pointScore         472 non-null    object
 1   gameScore          472 non-null    object
 2   setScore           472 non-null    object
 3   isPointStart       118 non-null    float64
 4   pointStartTime     471 non-null    float64
 5   isPointEnd         118 non-null    float64
 6   pointEndTime       117 non-null    float64
 7   pointNumber        472 non-null    int64
 8   isBreakPoint       81 non-null     float64
 9   shotInRally        472 non-null    int64
 10  side               472 non-null    object
 11  serverName         472 non-null    object
 12  serverFarNear      472 non-null    object
 13  firstServeIn       116 non-null    float64
 14  firstServeZone     116 non-null    object
 15  firstServeXCoord   116 non-null    float64
 16  firstServeYCoord   116 non-null    float64
 17  secondServeIn      45 non-null     float64
 18  secondServeZone    45 non-null     object
 19  secondServeXCoord  45 non-null     float64
 20  secondServeYCoord  45 non-null     float64
 21  isAce              5 non-null      float64
 22  shotContactX       465 non-null    float64
 23  shotContactY       465 non-null    float64
 24  shotDirection      354 non-null    object
 25  shotFhBh           351 non-null    object
 26  isSlice            70 non-null     float64
 27  isVolley           3 non-null      float64
 28  isOverhead         2 non-null      float64
 29  isApproach         1 non-null      float64
 30  isDropshot         1 non-null      float64
 31  isExcitingPoint    0 non-null      float64
 32  atNetPlayer1       3 non-null      float64
 33  atNetPlayer2       1 non-null      float64
 34  isLob              0 non-null      float64
 35  shotLocationX      355 non-null    float64
 36  shotLocationY      355 non-null    float64
 37  isWinner           26 non-null     float64
 38  isErrorWideR       8 non-null      float64
 39  isErrorWideL       10 non-null     float64
 40  isErrorNet         59 non-null     float64
 41  isErrorLong        31 non-null     float64
 42  clientTeam         472 non-null    object
 43  Date               472 non-null    object
 44  Division           472 non-null    object
 45  Event              472 non-null    object
 46  lineupPosition     1 non-null      float64
 47  matchDetails       0 non-null      float64
 48  matchVenue         472 non-null    object
 49  opponentTeam       472 non-null    object
 50  player1Name        472 non-null    object
 51  player2Name        472 non-null    object
 52  player1Hand        472 non-null    object
 53  player2Hand        472 non-null    object
 54  Round              0 non-null      float64
 55  Surface            472 non-null    object
 56  Notes              0 non-null      float64
 57  isTopspin          198 non-null    float64
 58  isFlat             166 non-null    float64
 59  isKick             10 non-null     float64
 60  gameNumber         472 non-null    int64
 61  tiebreakScore      0 non-null      float64
 62  returnerName       472 non-null    object
 63  shotHitBy          472 non-null    object
 64  InsideOut          52 non-null     float64
 65  InsideIn           54 non-null     float64
 66  isDoubleFault      5 non-null      float64
 67  pointWonBy         118 non-null    object
 68  lastShotError      86 non-null     float64
 69  serveResult        118 non-null    object
 70  serveInPlacement   114 non-null    object
 71  depth              274 non-null    object
dtypes: float64(42), int64(3), object(27)
memory usage: 265.6+ KB

`df.describe()`

In [22]:
shots.describe()

,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,firstServeIn,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,lineupPosition,matchDetails,Round,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,InsideOut,InsideIn,isDoubleFault,lastShotError
count,118.0,4.710000e+02,118.0,1.170000e+02,472.000000,81.0,472.000000,116.000000,116.000000,116.000000,45.000000,45.000000,45.000000,5.0,465.000000,465.000000,70.0,3.0,2.0,1.0,1.0,0.0,3.0,1.0,0.0,355.000000,355.000000,26.0,8.0,10.0,59.0,31.0,1.0,0.0,0.0,0.0,198.0,166.0,10.0,472.000000,0.0,52.0,54.0,5.0,86.0
mean,1.0,2.284684e+06,1.0,2.213681e+06,62.103814,1.0,3.508475,0.612069,1.018972,6.278533,0.622222,-0.555828,81.510268,1.0,-1.876645,4.458188,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-2.562345,24.169400,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,10.726695,NaN,1.0,1.0,1.0,1.0
std,0.0,1.311719e+06,0.0,1.325135e+06,33.705478,0.0,2.926548,0.489393,92.930666,214.363255,0.490310,88.823415,204.013913,0.0,95.061139,467.252608,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,91.833594,323.553549,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,5.647415,NaN,0.0,0.0,0.0,0.0
min,1.0,2.502000e+04,1.0,3.854900e+04,1.000000,1.0,1.000000,0.000000,-174.907409,-357.316240,0.000000,-158.068099,-246.000000,1.0,-205.137932,-559.000000,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-212.856419,-564.116366,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.000000,NaN,1.0,1.0,1.0,1.0
25%,1.0,1.211054e+06,1.0,1.057069e+06,35.000000,1.0,1.750000,0.000000,-61.205370,-187.465984,0.000000,-69.107048,-154.447643,1.0,-74.721325,-463.143203,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-79.483648,-276.164348,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,6.000000,NaN,1.0,1.0,1.0,1.0
50%,1.0,2.285176e+06,1.0,2.169659e+06,63.500000,1.0,3.000000,1.000000,9.132191,-113.950990,1.000000,-20.160176,195.738840,1.0,2.667946,223.427882,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,-3.123704,8.803128,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,11.000000,NaN,1.0,1.0,1.0,1.0
75%,1.0,3.438290e+06,1.0,3.410780e+06,90.250000,1.0,4.000000,1.000000,50.516820,241.978628,1.000000,73.484843,245.380430,1.0,61.862844,469.234558,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,72.984052,321.674459,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,15.250000,NaN,1.0,1.0,1.0,1.0
max,1.0,4.457669e+06,1.0,4.457669e+06,118.000000,1.0,19.000000,1.000000,183.301438,426.971867,1.000000,179.708809,365.158361,1.0,250.000000,617.555862,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,227.304560,648.075066,1.0,1.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,20.000000,NaN,1.0,1.0,1.0,1.0

`df.shape`

In [24]:
shots.shape

(472, 72)

`len()`

In [25]:
len(shots)

472

In [ ]:
sample_data = range(0, 10)
len(sample_data)
# list(sample_data)

In [ ]:
sample_data = data['Name']
len(sample_data)
# data['Name']

### How to Subset your Dataframe
One Column: `df[]`

Multiple Columns: `df[[ ]]`

In [30]:
shots[['pointScore']].head()

  pointScore
0        0-0
1        0-0
2        0-0
3        0-0
4       15-0

In [31]:
shots[['pointScore', 'isPointStart']].head()

  pointScore  isPointStart
0        0-0           1.0
1        0-0           NaN
2        0-0           NaN
3        0-0           NaN
4       15-0           1.0

### How to Filter your dataframe

`df.loc[]` and `df.iloc[]`

`df.loc[df['column'] == 'condition']`

In [36]:
shots.loc[shots['InsideOut'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,40-0,0-0,0-0,NaN,105620.0,1.0,105620.0,4,NaN,2,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.081819,478.803674,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-168.478341,-193.353565,NaN,1.0,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
15,0-0,1-0,0-0,NaN,158580.0,1.0,158580.0,5,NaN,3,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-25.773075,-370.143373,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.902909,468.458503,NaN,1.0,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,2,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
30,30-30,1-0,0-0,NaN,278220.0,NaN,NaN,9,NaN,8,Deuce,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-45.602811,475.215256,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.823628,-341.704112,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,2,NaN,Kaylan Bigun,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
36,30-40,1-0,0-0,NaN,311119.0,1.0,311119.0,10,1.0,3,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-41.491076,-518.165622,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.013648,497.221315,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,2,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
52,15-30,2-0,0-0,NaN,451510.0,NaN,NaN,14,NaN,5,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-36.015015,-472.114250,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.486160,244.696161,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,3,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,15-30,2-0,0-0,NaN,452950.0,1.0,452950.0,14,NaN,6,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.340360,399.858465,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-16.960876,26.147113,NaN,NaN,NaN,1.0,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,3,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Short
73,30-0,2-1,0-0,NaN,700559.0,1.0,700559.0,20,NaN,5,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.923414,481.195954,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.290857,0.430151,NaN,NaN,NaN,1.0,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,4,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN
79,40-30,2-1,0-0,NaN,795479.0,NaN,NaN,23,NaN,3,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-85.523977,-531.622211,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.567563,336.333847,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,4,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,40-40,2-1,0-0,NaN,816679.0,NaN,NaN,24,1.0,2,Deuce,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.842334,-484.075645,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-97.795068,221.335652,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,4,NaN,Kaylan Bigun,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
137,30-0,4-2,0-0,NaN,1405500.0,NaN,NaN,41,NaN,2,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.087937,-460.152854,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37.979631,383.840108,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,7,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
138,30-0,4-2,0-0,NaN,1406770.0,1.0,1406770.0,41,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-43.621697,466.244209,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.450848,237.880999,NaN,NaN,NaN,1.0,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,7,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,Nathan Trouve,1.0,NaN,NaN,NaN
141,30-15,4-2,0-0,NaN,1429369.0,NaN,NaN,42,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.917930,488.372791,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.343564,-190.188293,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,7,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
150,30-30,4-2,0-0,NaN,1465369.0,NaN,NaN,43,NaN,7,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-12.737030,457.273163,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.931261,-114.186466,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,7,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
156,30-40,4-2,0-0,NaN,1500170.0,1.0,1500170.0,44,1.0,2,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-119.987763,-520.856917,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.571604,504.741071,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,7,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
162,0-0,4-3,0-0,NaN,1627099.0,NaN,NaN,46,NaN,3,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.054724,427.369674,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-120.838189,-317.819827,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,8,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
177,0-15,4-4,0-0,NaN,1756949.0,1.0,1756949.0,51,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.990245,426.173535,Crosscourt,Forehand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,147.062314,-336.232376,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,9,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,Kaylan Bigun,NaN,NaN,NaN,NaN
179,15-15,4-4,0-0,NaN,1784199.0,NaN,NaN,52,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-19.549399,493.157349,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.622397,-327.101028,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,9,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
183,15-15,4-4,0-0,NaN,1790270.0,NaN,NaN,52,NaN,6,Ad,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.770828,455.478953,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-108.319526,-190.872140,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,9,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
187,15-30,4-4,0-0,NaN,1831430.0,NaN,NaN,53,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.922375,-449.686614,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-93.747446,351.796123,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,9,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
191,15-30,4-4,0-0,NaN,1836199.0,1.0,1836199.0,53,NaN,7,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.137730,-510.689731,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-157.661297,648.075066,NaN,NaN,1.0,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,9,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,Nathan Trouve,1.0,NaN,NaN,NaN
224,40-30,4-5,0-0,NaN,2165959.0,NaN,NaN,60,NaN,4,Deuce,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-17.680435,445.311767,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.583842,-292.651367,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,10,NaN,Kaylan Bigun,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
231,0-0,5-5,0-0,NaN,2237060.0,NaN,NaN,62,NaN,2,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.948874,-450.284684,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.550749,245.360871,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,11,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
232,0-0,5-5,0-0,NaN,2238449.0,NaN,NaN,62,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.358831,399.260395,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.258372,-364.658700,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,11,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
248,40-30,5-5,0-0,NaN,2397389.0,NaN,NaN,67,NaN,5,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-71.618865,450.694395,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.235728,-167.035203,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,11,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
252,40-40,5-5,0-0,NaN,2425079.0,NaN,NaN,68,NaN,2,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.000000,-488.000000,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-29.000000,432.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,11,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
253,40-40,5-5,0-0,NaN,2426680.0,1.0,2427646.0,68,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-72.000000,485.000000,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131.000000,-466.000000,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,11,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,Nathan Trouve,1.0,NaN,NaN,Long
258,0-0,5-6,0-0,NaN,2524929.0,NaN,NaN,69,NaN,5,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.489452,429.163883,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-154.253735,-341.944948,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,12,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
274,15-30,5-6,0-0,NaN,2622659.0,NaN,NaN,72,NaN,3,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.821435,464.450000,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-137.948037,-368.810663,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,12,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
276,15-30,5-6,0-0,NaN,2625459.0,1.0,2625459.0,72,NaN,5,Ad,Nathan Trouve,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.646987,475.215256,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-108.005506,-248.525377,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,12,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Nathan Trouve,NaN,NaN,NaN,Short
279,30-30,5-6,0-0,NaN,2653193.0,NaN,NaN,73,NaN,3,Deuce,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-42.000000,476.000000,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.000000,-264.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,12,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
285,30-30,5-6,0-0,NaN,2660685.0,NaN,NaN,73,NaN,9,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.000000,415.000000,Crosscourt,Backhand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-62.000000,-260.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,12,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
286,30-30,5-6,0-0,NaN,2662445.0,NaN,NaN,73,NaN,10,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-94.000000,-477.000000,Crosscourt,Forehand,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.000000,294.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,12,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
288,30-30,5-6,0-0,NaN,2664918.0,NaN,NaN,73,NaN,12,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-129.000000,-480.000000,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,302.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,12,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
289,30-30,5-6,0-0,NaN,2666049.0,NaN,NaN,73,NaN,13,Ad,Kaylan Bigun,Far,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.000000,474.000000,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-73.000000,-290.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,12,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Short
314,0-0,0-1,0-1,NaN,3058719.0,NaN,NaN,80,NaN,3,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-43.023628,-495.139917,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.435357,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,0-0,0-1,0-1,NaN,3061449.0,NaN,NaN,80,NaN,5,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-43.920751,-502.017738,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.668509,374.325727,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep

In [37]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [38]:
shots.iloc[0, 4]

25020.0

### Conditional Subsetting & Querying
`&`

`|`

In [39]:
shots['serverName'].head()

0    Kaylan Bigun
1    Kaylan Bigun
2    Kaylan Bigun
3    Kaylan Bigun
4    Kaylan Bigun
Name: serverName, dtype: object

In [42]:
shots.loc[(shots['serverName'] == 'Kaylan Bigun') & (shots['isAce'] == 1)]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

`.query()`
1. Filter when the `serverName` is equal to `Kaylan Bigun`
2. Also Filter all of his Aces

Can use many conditions (==, != , >, <, >=, <=)

In [49]:
shots_excel = pd.read_excel('data/(playsight)kaylan_usc.xlsx', sheet_name = 'Shots')
shots_excel.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Kaylan Bigun,1,first_serve,Serve,Slice,86.335464,1,1,1,deep,deuce,far,-0.492128,19.061304,deep,deuce,near,0.978027,0.181941,2.421875,down the T,Out,False,22:45:24,25.020000
1,Nathan Trouve,1,none,Backhand,Flat,35.898598,1,1,1,deep,ad,near,-1.200108,5.485592,deep,deuce,far,-0.909668,24.365038,1.114258,inside in,In,False,22:45:25,26.020000
2,Kaylan Bigun,1,second_serve,Serve,Slice,81.066826,1,1,1,short,deuce,far,-0.779633,15.777584,deep,deuce,near,0.976562,0.518099,2.332031,down the T,In,False,22:45:34,35.220001
3,Nathan Trouve,2,second_return,Backhand,Flat,61.041412,1,1,1,deep,deuce,near,0.660032,2.415293,deep,deuce,far,-1.298828,23.865038,0.971680,inside out,In,False,22:45:35,36.320000
4,Kaylan Bigun,3,serve_plus_one,Forehand,Topspin,62.817978,1,1,1,out,deuce,far,-1.314453,25.694525,deep,deuce,near,0.910156,-0.470559,0.833008,inside out,Out,False,22:45:36,37.349998

In [44]:
shots.query('serverName == "Kaylan Bigun" and isAce == 1')

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.0,201.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [50]:
shots_excel.columns

Index(['Player', 'Shot', 'Type', 'Stroke', 'Spin', 'Speed (MPH)', 'Point',
       'Game', 'Set', 'Bounce Depth', 'Bounce Zone', 'Bounce Side',
       'Bounce (x)', 'Bounce (y)', 'Hit Depth', 'Hit Zone', 'Hit Side',
       'Hit (x)', 'Hit (y)', 'Hit (z)', 'Direction', 'Result', 'Favorited',
       'Start Time', 'Video Time'],
      dtype='object')

In [53]:
shots_excel.query('`Speed (MPH)` > 100').head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
6,Kaylan Bigun,1,second_serve,Serve,Flat,110.786316,2,1,1,deep,ad,far,2.284124,19.640869,deep,ad,near,-2.001953,0.623191,2.349609,down the T,Out,False,22:46:43,104.949997
11,Nathan Trouve,1,first_serve,Serve,Flat,115.043945,4,1,1,deep,ad,far,2.898438,18.296926,deep,ad,near,-1.217773,0.203817,2.269531,out wide,Out,False,22:48:03,184.279999
17,Nathan Trouve,1,second_serve,Serve,Slice,120.689171,5,2,1,deep,deuce,far,-1.173526,21.427223,deep,deuce,near,0.915527,0.252415,2.164062,down the T,Out,False,22:48:40,221.880005
22,Nathan Trouve,1,first_serve,Serve,Slice,110.410797,7,2,1,short,deuce,far,-1.324739,18.212114,deep,deuce,near,1.223633,0.615378,2.371094,down the T,In,False,22:49:28,269.149994
33,Nathan Trouve,1,first_serve,Serve,Kick,103.583366,8,2,1,deep,deuce,far,-0.481523,20.106646,deep,ad,near,-1.806641,0.427878,2.490234,down the T,Out,False,22:49:58,299.350006

### Summarizing the Data (Numerical)
`.mean()`

`.max()`

`.min()`

`.std()`

`.var()`

`.quantile`

In [55]:
shots_excel['Speed (MPH)'].mean()

60.6992050367647

### Can also do for multiple Columns
`df[['column', 'column', ...]].mean()`

In [57]:
shots_excel[['Speed (MPH)', 'Bounce (x)']].max()

Speed (MPH)    130.596954
Bounce (x)       5.938494
dtype: float64

### Use the Aggregate Function

`.agg()`

`df[['column', 'column', ...]].agg(['mean', 'sum', 'max'])`

In [58]:
shots_excel[['Speed (MPH)', 'Bounce (x)']].agg(['mean', 'sum', 'max'])

       Speed (MPH)  Bounce (x)
mean     60.699205   -0.034155
sum   33020.367540  -18.580325
max     130.596954    5.938494

`.sum()`

In [59]:
shots_excel['Speed (MPH)'].sum()

33020.36754

`.count()`

In [62]:
shots_excel['Speed (MPH)'].count()
shots_excel.shape

(544, 25)

### Summarizing the Data (Categorial)

`.unique()`

In [64]:
shots_excel['Stroke'].unique()

array(['Serve', 'Backhand', 'Forehand', 'Feed', 'Volley', 'Overhead'],
      dtype=object)

`.nunique()`

Same as len(df.unique())

In [65]:
shots_excel['Stroke'].nunique()

6

`.value_counts()`

Arguments: normalize (True, False)


Find the value counts of `firstServeZone`

Find the value counts of `firstServeZone` and `firstServeIn`

In [66]:
shots_excel['Stroke'].value_counts()

Stroke
Forehand    220
Serve       157
Backhand    147
Feed         15
Volley        3
Overhead      2
Name: count, dtype: int64

### GroupBy Methods
`df.groupby()`

In [67]:
shots.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
0,0-0,0-0,0-0,1.0,25020.0,NaN,NaN,1,NaN,1,Deuce,Kaylan Bigun,Near,0.0,T,-18.83692,274.599344,1.0,T,-29.841596,148.910149,NaN,37.379342,-435.169001,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,2.0,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,2nd Serve In,T,NaN
1,0-0,0-0,0-0,NaN,36320.0,NaN,NaN,1,NaN,2,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-49.714545,458.469302,Crosscourt,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.263692,-362.551121,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,1.0,NaN,1,NaN,Nathan Trouve,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
2,0-0,0-0,0-0,NaN,37349.0,NaN,NaN,1,NaN,3,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.837555,-473.011335,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-50.312615,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,38549.0,1.0,38549.0,1,NaN,4,Deuce,Kaylan Bigun,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-55.284077,511.099442,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.758722,-484.903489,NaN,NaN,NaN,NaN,1.0,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,1,NaN,Nathan Trouve,Nathan Trouve,NaN,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,Long
4,15-0,0-0,0-0,1.0,57814.0,1.0,61681.0,2,NaN,1,Ad,Kaylan Bigun,Near,1.0,Wide,149.00000,201.000000,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,1,NaN,Nathan Trouve,Kaylan Bigun,NaN,NaN,NaN,Kaylan Bigun,NaN,1st Serve In,Wide,NaN

In [70]:
shots.groupby('pointNumber')['InsideOut'].sum()
shots[shots['pointNumber'] == 80]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,side,serverName,serverFarNear,firstServeIn,firstServeZone,firstServeXCoord,firstServeYCoord,secondServeIn,secondServeZone,secondServeXCoord,secondServeYCoord,isAce,shotContactX,shotContactY,shotDirection,shotFhBh,isSlice,isVolley,isOverhead,isApproach,isDropshot,isExcitingPoint,atNetPlayer1,atNetPlayer2,isLob,shotLocationX,shotLocationY,isWinner,isErrorWideR,isErrorWideL,isErrorNet,isErrorLong,clientTeam,Date,Division,Event,lineupPosition,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,isTopspin,isFlat,isKick,gameNumber,tiebreakScore,returnerName,shotHitBy,InsideOut,InsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
312,0-0,0-1,0-1,1.0,3056419.0,NaN,NaN,80,NaN,1,Deuce,Nathan Trouve,Near,1.0,Wide,-154.224645,244.409509,NaN,NaN,NaN,NaN,NaN,48.817460,-452.676963,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,NaN,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,NaN,NaN,NaN,NaN,NaN,1st Serve In,Wide,NaN
313,0-0,0-1,0-1,NaN,3057340.0,NaN,NaN,80,NaN,2,Deuce,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-190.784257,453.086674,Down the Line,Backhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-64.624989,-394.480468,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deep
314,0-0,0-1,0-1,NaN,3058719.0,NaN,NaN,80,NaN,3,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-43.023628,-495.139917,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.435357,455.000000,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,0-0,0-1,0-1,NaN,3060040.0,NaN,NaN,80,NaN,4,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.330293,464.450000,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21.257180,-336.011062,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
316,0-0,0-1,0-1,NaN,3061449.0,NaN,NaN,80,NaN,5,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-43.920751,-502.017738,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.668509,374.325727,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Deep
317,0-0,0-1,0-1,NaN,3062520.0,NaN,NaN,80,NaN,6,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.912970,491.363140,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-34.613369,-205.702204,NaN,NaN,NaN,NaN,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Kaylan Bigun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Short
318,0-0,0-1,0-1,NaN,3063840.0,1.0,3063840.0,80,NaN,7,Ad,Nathan Trouve,Near,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-88.439572,-490.953428,Crosscourt,Forehand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.359662,-212.779943,NaN,NaN,NaN,1.0,NaN,"Univeristy of California, Los Angeles",2/22/15,Division 1,Dual-Match,NaN,NaN,Los Angeles Tennis Center,University of South California,Kaylan Bigun,Nathan Trouve,Left,Right,NaN,Hard,NaN,1.0,NaN,NaN,14,NaN,Kaylan Bigun,Nathan Trouve,1.0,NaN,NaN,Kaylan Bigun,1.0,NaN,NaN,NaN

### Handling Missing Values
`.isna()`

`.dropna()`

`.fillna()`

In [71]:
shots.isna().sum()

pointScore             0
gameScore              0
setScore               0
isPointStart         354
pointStartTime         1
isPointEnd           354
pointEndTime         355
pointNumber            0
isBreakPoint         391
shotInRally            0
side                   0
serverName             0
serverFarNear          0
firstServeIn         356
firstServeZone       356
firstServeXCoord     356
firstServeYCoord     356
secondServeIn        427
secondServeZone      427
secondServeXCoord    427
secondServeYCoord    427
isAce                467
shotContactX           7
shotContactY           7
shotDirection        118
shotFhBh             121
isSlice              402
isVolley             469
isOverhead           470
isApproach           471
isDropshot           471
isExcitingPoint      472
atNetPlayer1         469
atNetPlayer2         471
isLob                472
shotLocationX        117
shotLocationY        117
isWinner             446
isErrorWideR         464
isErrorWideL         462
isErrorNet           413
isErrorLong          441
clientTeam             0
Date                   0
Division               0
Event                  0
lineupPosition       471
matchDetails         472
matchVenue             0
opponentTeam           0
player1Name            0
player2Name            0
player1Hand            0
player2Hand            0
Round                472
Surface                0
Notes                472
isTopspin            274
isFlat               306
isKick               462
gameNumber             0
tiebreakScore        472
returnerName           0
shotHitBy              0
InsideOut            420
InsideIn             418
isDoubleFault        467
pointWonBy           354
lastShotError        386
serveResult          354
serveInPlacement     358
depth                198
dtype: int64

### How to save/write your CSV
`.to_csv()`

In [72]:
df.to_csv('cats.csv')

### Problems to Practice Yourself!!

#### Problem 1: From the `Shot_Visuals_KaylanBigun_NathanTrouve.csv` dataset, create two tables
1. Table of the **counts** of the zones Kaylan had served into for his firstServe (including made adn missed)
1. Table of the **percentage** of the zones Kaylan had served into for his firstServe ((including made adn missed))

In [74]:
# Subsetting
# Conditional/Querying 
# value_counts()

shots['firstServeZone'].value_counts()

firstServeZone
T       58
Wide    41
Body    17
Name: count, dtype: int64

In [77]:
total = shots['firstServeZone'].count()
shots['firstServeZone'].value_counts() / total

firstServeZone
T       0.500000
Wide    0.353448
Body    0.146552
Name: count, dtype: float64

#### Problem 2: From the `(playsight)kaylan_usc.xlsx` dataset (Download from slack!)
Find the minimum, maximum, and average speed of Kaylan's stroke type

In [78]:
# .agg() (.max(), .mean(), .sum())
# value_counts()
shots_excel.head()

,Player,Shot,Type,Stroke,Spin,Speed (MPH),Point,Game,Set,Bounce Depth,Bounce Zone,Bounce Side,Bounce (x),Bounce (y),Hit Depth,Hit Zone,Hit Side,Hit (x),Hit (y),Hit (z),Direction,Result,Favorited,Start Time,Video Time
0,Kaylan Bigun,1,first_serve,Serve,Slice,86.335464,1,1,1,deep,deuce,far,-0.492128,19.061304,deep,deuce,near,0.978027,0.181941,2.421875,down the T,Out,False,22:45:24,25.020000
1,Nathan Trouve,1,none,Backhand,Flat,35.898598,1,1,1,deep,ad,near,-1.200108,5.485592,deep,deuce,far,-0.909668,24.365038,1.114258,inside in,In,False,22:45:25,26.020000
2,Kaylan Bigun,1,second_serve,Serve,Slice,81.066826,1,1,1,short,deuce,far,-0.779633,15.777584,deep,deuce,near,0.976562,0.518099,2.332031,down the T,In,False,22:45:34,35.220001
3,Nathan Trouve,2,second_return,Backhand,Flat,61.041412,1,1,1,deep,deuce,near,0.660032,2.415293,deep,deuce,far,-1.298828,23.865038,0.971680,inside out,In,False,22:45:35,36.320000
4,Kaylan Bigun,3,serve_plus_one,Forehand,Topspin,62.817978,1,1,1,out,deuce,far,-1.314453,25.694525,deep,deuce,near,0.910156,-0.470559,0.833008,inside out,Out,False,22:45:36,37.349998

In [83]:
kaylan = shots_excel.query('Player == "Kaylan Bigun"')
kaylan['Speed (MPH)'].agg(['max', 'mean', 'sum'])

max       130.596954
mean       61.523458
sum     16365.239721
Name: Speed (MPH), dtype: float64